package com.reading;

public class GenUppToLow {

	public static void main(String[] args) {
		String input = "outputCode,SACCTNO,CUSTNO,CUST_ID_NO,IDTYPE,ACCNAME,ADDRESS1,ADDRESS2,FIELD1,ADDRESS3,CURRENC3,ADDRESS4,POSTCODE,ACCTTYPE,INTCAT,LEGALENT,SPACE1,INTPAYMETHOD,SPACE2,TFRACCTNO,CHEXPRO,LANGCODE,FREQ,SPACE3,STDAIND,MAILIND,NOTIND,NOTCUST,VAINRATE,SPACE4,INTFREQ,CYCLE,DAY,AGENTCD,INVTYPE,DISTRICT,SEGMENT_CODE,SPACE5,BUSSINESS_TYPE,SPACE6,GROUPIND,FACNO,APPLID,SPACE7,VISAFLAG,VISECODE,VICRLIM,SPACE8,TERMLENGTH,FREQUENCY_CODE,TERMVAL,SPACE9,TIGRID,CURIDORI,CUSTRISK,ARCBRISK,SECIND,TIMEBAND,BANKID,SPACE10,OPENDATE,COPIES,FILLER5,ACEXIND,MATRATE,FILLER6,CERTIFICATENO,RATE_TYPE,STAMP_TAX_FLAG,RATEINCR,REFERRAL,SPACE11,GLCC,SECURITYNO,EMPNO,OMNIBUS,PROMCODE,SPACE12,INVESTCODE,OMNIBUSACCT,TLR_FLAG,RT_LIMIT,INVESTTYPE,TRUST_PROD_MEMO,PUBLISH_NO,BILLS_NO,PORTFOLIO_NO,OPEN_PURPOSE,NCD_REGISTERED,PERSON_FLAG,AUTO_ROLL,MNTHY_ESTI_DEP_CNT,MNTHY_ESTI_DEP_AMT_TWD,MNTHY_ESTI_DEP_AMT_USD,MNTHY_ESTI_WDL_CNT,MNTHY_ESTI_WDL_AMT_TWD,MNTHY_ESTI_WDL_AMT_USD,I_USE_FLAG";

		String[] inputArray = input.split(",");

		for (int i = 0; i < inputArray.length; i++) {
			String[] lowerInputArray = inputArray[i].toLowerCase().split("_");
			String temp = "";
			for (int j = 0; j < lowerInputArray.length; j++) {
				if (j == 0) {
					temp += lowerInputArray[j].trim();
				} else {
					String firstWord = new StringBuilder().append("").append(lowerInputArray[j].charAt(0)).toString();
					temp += lowerInputArray[j].replaceFirst(firstWord, firstWord.toUpperCase()).trim();
				}
			}
			System.out.println("private String " + temp + ";");
		}
	}

}
